-- MySQL Script generated by MySQL Workbench
-- Fri Feb 24 00:41:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clearance_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clearance_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clearance_db` DEFAULT CHARACTER SET latin5 ;
USE `clearance_db` ;

-- -----------------------------------------------------
-- Table `clearance_db`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clearance_db`.`students` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(1) NOT NULL,
  `birthday` DATE NOT NULL,
  `contact_no` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clearance_db`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clearance_db`.`courses` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clearance_db`.`course_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clearance_db`.`course_year` (
  `course_year_id` INT NOT NULL AUTO_INCREMENT,
  `year_name` VARCHAR(45) NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`course_year_id`, `course_id`),
  INDEX `fk_course_year_courses1_idx` (`course_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clearance_db`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clearance_db`.`sections` (
  `section_id` INT NOT NULL AUTO_INCREMENT,
  `section_name` VARCHAR(45) NOT NULL,
  `course_year_id` INT NOT NULL,
  PRIMARY KEY (`section_id`, `course_year_id`),
  INDEX `fk_sections_course_year_idx` (`course_year_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clearance_db`.`student_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clearance_db`.`student_details` (
  `student_detail_id` INT NOT NULL AUTO_INCREMENT,
  `semester` VARCHAR(45) NOT NULL,
  `course_id` INT NOT NULL,
  `course_year_id` INT NOT NULL,
  `section_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`student_detail_id`, `course_id`, `course_year_id`, `section_id`, `student_id`),
  INDEX `fk_student_details_courses1_idx` (`course_id` ASC),
  INDEX `fk_student_details_course_year1_idx` (`course_year_id` ASC),
  INDEX `fk_student_details_sections1_idx` (`section_id` ASC),
  INDEX `fk_student_details_students1_idx` (`student_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clearance_db`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clearance_db`.`subjects` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `subject_name` VARCHAR(45) NULL,
  `course_year_id` INT NOT NULL,
  PRIMARY KEY (`subject_id`, `course_year_id`),
  INDEX `fk_subjects_course_year1_idx` (`course_year_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clearance_db`.`student_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clearance_db`.`student_subject` (
  `student_detail_id` INT NOT NULL,
  `subjects_subject_id` INT NOT NULL,
  PRIMARY KEY (`student_detail_id`, `subjects_subject_id`),
  INDEX `fk_student_subject_subjects1_idx` (`subjects_subject_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
